Numpy Array operations

In [2]:
import numpy as np

## Indexing and Slicing

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic slicing: ", arr[2:7])
print("With step: ", arr[1:8:2])
print("Negative indexing: ", arr[-3])

Basic slicing:  [3 4 5 6 7]
With step:  [2 4 6 8]
Negative indexing:  8


In [10]:
arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print("Array: \n",arr_2d)

print("specific element: ", arr_2d[1,2]) ## element position in 2d matrixx
print("Entire row", arr_2d[1]) # for row
print("Entire column", arr_2d[:,2]) # for column
print("2d array slicing: \n",arr_2d[1:3, 1:3])

Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
specific element:  6
Entire row [4 5 6]
Entire column [3 6 9]
2d array slicing: 
 [[5 6]
 [8 9]]
