Numpy Array operations

In [3]:
import numpy as np

## Indexing and Slicing

In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic slicing: ", arr[2:7])
print("With step: ", arr[1:8:2])
print("Negative indexing: ", arr[-3])

Basic slicing:  [3 4 5 6 7]
With step:  [2 4 6 8]
Negative indexing:  8


In [5]:
arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print("Array: \n",arr_2d)

print("specific element: ", arr_2d[1,2]) ## element position in 2d matrixx
print("Entire row", arr_2d[1]) # for row
print("Entire column", arr_2d[:,2]) # for column
print("2d array slicing: \n",arr_2d[1:3, 1:3])

Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
specific element:  6
Entire row [4 5 6]
Entire column [3 6 9]
2d array slicing: 
 [[5 6]
 [8 9]]


Sorting

In [10]:
unsort = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted array: ", np.sort(unsort))

arr_2d_unsort = np.array([[3, 1],[1, 2],[2, 3]])
print("Sorted 2d col: \n", np.sort(arr_2d_unsort, axis = 0))
print("Sorted 2d row: \n", np.sort(arr_2d_unsort, axis = 1))

Sorted array:  [1 1 2 3 4 5 6 9]
Sorted 2d col: 
 [[1 1]
 [2 2]
 [3 3]]
Sorted 2d row: 
 [[1 3]
 [1 2]
 [2 3]]


## filter

In [15]:
num = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even = num[num % 2 == 0]
Odd = num[num % 2 != 0]
print("Even: ",even)
print("Odd: ",Odd)

Even:  [ 2  4  6  8 10]
Odd:  [1 3 5 7 9]


## Filter with mask

In [17]:
mask = num > 5
print("Numbers greater 5: ", num[mask])

Numbers greater 5:  [ 6  7  8  9 10]


## Indexing array vs np.where() 

In [24]:
indices = [0, 2, 4]
print(num[indices])

where_result = np.where(num > 5)

print("NP:",num[where_result])

print(where_result) # stores indices when condition is true

[1 3 5]
NP: [ 6  7  8  9 10]
(array([5, 6, 7, 8, 9]),)


In [28]:
condition_array = np.where(num > 5, num*2, num) # like if-else at particular slice
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20]


## Concate

In [31]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


## compatibility

In [35]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

print(a.shape == b.shape)

True


In [39]:
original = np.array([[1, 2],[3, 4]])
new_row = np.array([[5,6]])

w_row = np.vstack((original,new_row)) # Adding a row

print(original) 
print(w_row)

new_col = np.array([[7],[8]])
w_col = np.hstack((original,new_col))

print("with column: \n", w_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
with column: 
 [[1 2 7]
 [3 4 8]]


In [40]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr,2)
print("array after deletion: ", deleted)

array after deletion:  [1 2 4 5]
