## Broadcasting in numpy array

In [1]:
import numpy as np

In [3]:
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000], 
    [1, 120000, 140000, 160000, 190000], 
    [1, 200000, 230000, 260000, 300000], 
    [1, 180000, 210000, 240000, 270000], 
    [1, 160000, 185000, 205000, 230000] 
])

In [ ]:
monthly_avg = sales_data[:,1:] /12
print(monthly_avg)

## this scalar number streched for the vector operation
## it's called broadcasting it implements at every position of vector element
## individually

[[12500.         15000.         18333.33333333 20833.33333333]
 [10000.         11666.66666667 13333.33333333 15833.33333333]
 [16666.66666667 19166.66666667 21666.66666667 25000.        ]
 [15000.         17500.         20000.         22500.        ]
 [13333.33333333 15416.66666667 17083.33333333 19166.66666667]]
